### PR TITLE
Material for the "Modal editing in vi/vim" tech-talk

### PR DESCRIPTION
**Pull request by notarock**
I have the recording, but since it is over 100Mb, Github wouldn't let me upload it to this repo :/

I also corrected the README by removing a talk I didn't do.

### CODE REVIEW

**Comment by nixin72** [comment]
@notarock are you going to upload the video, or should I accept this as is?

**Comment by notarock** [comment]
> @notarock are you going to upload the video, or should I accept this as is?

I almost forgot about the video, thanks for the reminder. I will upload it later today for sure!

**Comment by notarock** [comment]
I added the recording, it's ready for merging  :+1:

**Review by nixin72 — APPROVED** [review]
Thank you! And I'll get the video uploaded to YouTube as soon as I can.

**Pull request merged**
